#!/usr/bin/env python3
"""Generate night_sky_tables.rs from the digitized Leinert 1998 tables.

Input: tools/leinert1998_tables.json (digitized + cross-checked grids;
see the JSON 'notes' fields for full provenance).
Output: crates/twilight-threshold/src/night_sky_tables.rs

Blank/unmapped cells (-1) are filled at generation time:
- zodiacal (8 cells unobservably close to the Sun): nearest valid value
  along the same latitude row — these directions only matter in daylight,
  where the twilight radiance dwarfs the zodiacal floor anyway.
- starlight (28 cells Pioneer never mapped, l=170-240 b=+16..+50):
  linear interpolation along the latitude row between valid neighbors.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "leinert1998_tables.json")
DST = os.path.join(
    HERE, "..", "crates", "twilight-threshold", "src", "night_sky_tables.rs"
)

with open(SRC) as f:
    t = json.load(f)


def fill_row_nearest(row):
    """Replace -1 with the nearest valid value in the row."""
    n = len(row)
    out = list(row)
    for i, v in enumerate(out):
        if v >= 0:
            continue
        best, bd = None, 10**9
        for j, w in enumerate(row):
            if w >= 0 and abs(j - i) < bd:
                best, bd = w, abs(j - i)
        out[i] = best
    return out


def fill_row_interp(row):
    """Replace -1 runs with linear interpolation between valid neighbors
    (wraparound in longitude)."""
    n = len(row)
    out = list(row)
    for i, v in enumerate(out):
        if v >= 0:
            continue
        # find prev/next valid with wrap
        p = (i - 1) % n
        while row[p] < 0:
            p = (p - 1) % n
        q = (i + 1) % n
        while row[q] < 0:
            q = (q + 1) % n
        dp = (i - p) % n
        dq = (q - i) % n
        out[i] = (row[p] * dq + row[q] * dp) / (dp + dq)
    return out


z = t["zodiacal"]
s = t["starlight"]

zvals = [fill_row_nearest(r) for r in z["values_s10"]]
svals = [fill_row_interp(r) for r in s["values_s10"]]


def fmt_grid(vals, per_row):
    lines = []
    for r in vals:
        cells = ", ".join(f"{v:.0f}." for v in r)
        lines.append(f"    [{cells}],")
    return "\n".join(lines)


rust = f"""//! Measured diffuse night-sky brightness tables (NOT fits).
//!
//! Generated by tools/gen_night_sky_tables.py from
//! tools/leinert1998_tables.json — do not edit by hand.
//!
//! ZODIACAL: Leinert et al. 1998 (A&AS 127, 1) Table 16 — the annually
//! averaged zodiacal light at 500 nm in S10_sun units on a helioecliptic
//! grid; ground photometry extended sunward with Helios A/B and rocket
//! data. Cross-checked cell-by-cell against the publisher's full-text
//! table and the independent skysim digitization (exact match, 190/190).
//! The 8 cells unobservably close to the Sun are filled with the nearest
//! row value (they only matter in daylight).
//!
//! STARLIGHT: Leinert 1998 Table 35 — Pioneer 10/11 imaging
//! photopolarimeter background starlight at 440 nm (Toller 1981) in
//! S10_sun per square degree, galactic grid, measured beyond 2.8 AU where
//! zodiacal light is undetectable. Includes diffuse galactic light;
//! resolved stars brighter than ~6.5 mag removed. Photometric accuracy
//! ~10%; transcribed from the publisher's page scan (no machine-readable
//! copy exists), every cell read twice. The 28 unmapped cells
//! (l=170-240, b=+16..+50) are filled by row interpolation.

/// Helioecliptic longitude difference grid [deg] for the zodiacal table.
pub const ZODI_DLON: [f64; {len(z["dlon_grid_deg"])}] = {json.dumps([float(v) for v in z["dlon_grid_deg"]]).replace('"', '')};

/// |Ecliptic latitude| grid [deg] for the zodiacal table.
pub const ZODI_LAT: [f64; {len(z["lat_grid_deg"])}] = {json.dumps([float(v) for v in z["lat_grid_deg"]]).replace('"', '')};

/// Zodiacal brightness [S10_sun at 500 nm], rows = ZODI_LAT, cols = ZODI_DLON.
pub const ZODI_S10: [[f64; {len(zvals[0])}]; {len(zvals)}] = [
{fmt_grid(zvals, len(zvals[0]))}
];

/// Galactic longitude grid [deg] for the starlight table.
pub const STAR_LON: [f64; {len(s["gal_lon_grid_deg"])}] = {json.dumps([float(v) for v in s["gal_lon_grid_deg"]]).replace('"', '')};

/// Galactic latitude grid [deg] for the starlight table.
pub const STAR_LAT: [f64; {len(s["gal_lat_grid_deg"])}] = {json.dumps([float(v) for v in s["gal_lat_grid_deg"]]).replace('"', '')};

/// Integrated starlight + DGL [S10_sun at 440 nm], rows = STAR_LAT, cols = STAR_LON.
pub const STAR_S10: [[f64; {len(svals[0])}]; {len(svals)}] = [
{fmt_grid(svals, len(svals[0]))}
];
"""

with open(DST, "w") as f:
    f.write(rust)
print(f"wrote {os.path.normpath(DST)}")
print(f"zodi {len(zvals)}x{len(zvals[0])}, star {len(svals)}x{len(svals[0])}")
# sanity anchors
b0 = s["gal_lat_grid_deg"].index(0)
print("star plane (b=0) median:", sorted(svals[b0])[len(svals[b0]) // 2])
print("zodi pole (75):", zvals[-1][0], "... gegenschein (lat0,dlon180):", zvals[0][-1])
