#!/usr/bin/env python3
"""Generate Rust LUTs from official NASA GIBS colormap XMLs.

Closes the provenance gap flagged in review: embedded colormaps must be
regenerable from their authoritative source. Downloads the v1.3 XMLs and
emits per-crate generated files. Bin VALUE = midpoint of the entry's
range; open-ended top bins use the lower edge (a floor — honest for
saturated city cores / very thick cloud).

Usage: python3 tools/gen_gibs_colormaps.py
"""

import os
import re
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = "https://gibs.earthdata.nasa.gov/colormaps/v1.3"

TARGETS = [
    # (xml name, rust const, crate-relative output, value transform, doc)
    ("VIIRS_DayNightBand_At_Sensor_Radiance",
     "DNB_RADIANCE_LUT",
     "crates/twilight-skyglow/src/dnb_colormap.rs",
     "Palette-index -> nighttime-lights radiance [nW/(cm^2 sr)]. Index 0 = nodata (-1.0)."),
    ("MODIS_Cloud_Water_Path",
     "CWP_COLORMAP",
     None,  # appended to the weather file below
     "RGB -> cloud water path [g/m^2]."),
    ("MODIS_VIIRS_Cloud_Effective_Radius",
     "REFF_COLORMAP",
     None,
     "RGB -> cloud particle effective radius [um]."),
]

WEATHER_OUT = "crates/twilight-weather/src/satellite_colormaps.rs"


def parse(xml_name):
    url = f"{BASE}/{xml_name}.xml"
    with urllib.request.urlopen(url, timeout=30) as r:
        xml = r.read().decode()
    out = []
    for tag in re.findall(r"<ColorMapEntry\b[^>]*>", xml):
        rgb = re.search(r'rgb="(\d+),(\d+),(\d+)"', tag)
        val = re.search(r'value="\[([^\]\)]+)[\]\)]"', tag)
        ref = re.search(r'ref="(\d+)"', tag)
        nodata = 'nodata="true"' in tag
        if not (rgb and ref):
            continue
        if nodata or not val:
            v = -1.0
        else:
            parts = [float(x) for x in val.group(1).split(",")]
            lo, hi = parts[0], parts[-1]
            v = lo if hi >= 999_999.0 else 0.5 * (lo + hi)
        out.append((int(ref.group(1)), tuple(int(x) for x in rgb.groups()), v, nodata))
    out.sort()
    return url, out


def rust_indexed(name, url, entries, doc):
    lines = [f"/// {doc}",
             f"/// Generated by tools/gen_gibs_colormaps.py from {url}",
             f"pub const {name}: [f64; {len(entries)}] = ["]
    for _, _, v, _ in entries:
        lines.append(f"    {v:.4},")
    lines.append("];")
    return "\n".join(lines)


def rust_rgb(name, url, entries, doc):
    valid = [(rgb, v) for _, rgb, v, nodata in entries if not nodata and v >= 0.0]
    lines = [f"/// {doc}",
             f"/// Generated by tools/gen_gibs_colormaps.py from {url}",
             f"pub const {name}: [(u8, u8, u8, f32); {len(valid)}] = ["]
    for (r, g, b), v in valid:
        lines.append(f"    ({r}, {g}, {b}, {v:.4}),")
    lines.append("];")
    return "\n".join(lines)


def main():
    root = os.path.dirname(HERE)

    url, entries = parse(TARGETS[0][0])
    body = ("//! Generated file — do not edit. Regenerate with\n"
            "//! `python3 tools/gen_gibs_colormaps.py`.\n\n"
            + rust_indexed("DNB_RADIANCE_LUT", url, entries, TARGETS[0][3]) + "\n")
    path = os.path.join(root, TARGETS[0][2])
    open(path, "w").write(body)
    print(f"wrote {TARGETS[0][2]} ({len(entries)} bins)")

    chunks = ["//! Generated file — do not edit. Regenerate with",
              "//! `python3 tools/gen_gibs_colormaps.py`.", ""]
    for xml_name, const, _, doc in TARGETS[1:]:
        url, entries = parse(xml_name)
        chunks.append(rust_rgb(const, url, entries, doc))
        chunks.append("")
        print(f"  {const}: {len(entries)} entries")
    open(os.path.join(root, WEATHER_OUT), "w").write("\n".join(chunks))
    print(f"wrote {WEATHER_OUT}")


if __name__ == "__main__":
    main()
